### ISSUE TITLE
PRAW 5.1 Incompatibility

### ISSUE THREAD

**Issue by jlnbxn** [csu/export-saved-reddit#46]
It doesn't seem to work after the upgrade from 4.4.0 to 5.1.0 after September 1, 2017.

**Comment by csu** [comment]
The [`requirements.txt`](https://github.com/csu/export-saved-reddit/blob/master/requirements.txt) file specifies praw version 4.4.0 still, so the script should be used with that. If you install requirements by running `pip install -r requirements.txt`, as described in the instructions in the readme, 4.4.0 will be installed.

Also, can you be more specific as to what you mean by "doesn't seem to work"?

**Comment by jlnbxn** [comment]
~~So, using 4.4.0 I just get the message "Version 4.4.0 of praw is outdated. Version 5.1.0 was released Friday September 01, 2017." in the shell when running export_saved.py, without any of the export files appearing in the folder. I was waiting about an hour, but still nothing happened. Next, I updated to version 5.1.0 of praw. Now, when trying to run the script, no messages appear, but the exporting doesn't work either - the script doesn't react and I'm unable to do further input in the shell. I retried it a few more times and even after extensive waiting, nothing happened.~~

While I was writing this, it has finally worked (with Version 4.4.0). I was initially discouraged because of the error message, but it looks like I really didn't gave it enough time for the exporting to be done - I'm not very knowledgeable about python yet.

I very much appreciate your work, your quick response and I apologize for using your time to compensate for my impatience.

**Comment by csu** [comment]
No problem. It's still valid feedback. We should eventually update to the latest version of praw, so users aren't confused by the warning message.

There's also a flag that you can run the script with to have it output progress as it runs, but it isn't set by default, so users with a lot of saved items instead just see the script get "stuck" for a long time (it can take a while due to the rate limit on the reddit API side) and they don't get any feedback that tells them the script is working. Perhaps we should enable the "verbose" output by default.

```
  -v, --verbose         increase output verbosity
```
